name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate secret
      run: php artisan jwt:secret
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: php artisan migrate
    - name: Seed database
      run: |
        php artisan db:seed --class=CreateMarcas
        php artisan db:seed --class=CreateCategorias
        php artisan db:seed --class=CreateUnidades
        php artisan db:seed --class=CreateProdutos
        php artisan db:seed --class=CreateFornecedores
        php artisan db:seed --class=CreateEntradas
        php artisan db:seed --class=CreateUsers
    - name: Execute tests via PHPUnit/Pest
      run: vendor/bin/phpunit
